// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvcwHAX07xA_GWS_dN6UfoeIZl55i_cs4',
    appId: '1:502219174600:web:b1d1a107df9fe996f7ebfd',
    messagingSenderId: '502219174600',
    projectId: 'nugard',
    authDomain: 'nugard.firebaseapp.com',
    storageBucket: 'nugard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM2A7xZ37Qoy7y6H63ATXvYjg4ECq6WJI',
    appId: '1:502219174600:android:3da532c4749368fcf7ebfd',
    messagingSenderId: '502219174600',
    projectId: 'nugard',
    storageBucket: 'nugard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCMnPlKy0mk2-bL8sxzrIPq-AuU7uOWmI',
    appId: '1:502219174600:ios:e09a5a593b948e6cf7ebfd',
    messagingSenderId: '502219174600',
    projectId: 'nugard',
    storageBucket: 'nugard.appspot.com',
    androidClientId: '502219174600-gtpct6np3n825cfa00q3p3rn2dd8af44.apps.googleusercontent.com',
    iosClientId: '502219174600-6lajedfb23f0mgsb5lifvmn2uvr4jlf4.apps.googleusercontent.com',
    iosBundleId: 'com.aa.NUStudentJourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvcwHAX07xA_GWS_dN6UfoeIZl55i_cs4',
    appId: '1:502219174600:web:f3a6938dd6a5a9d5f7ebfd',
    messagingSenderId: '502219174600',
    projectId: 'nugard',
    authDomain: 'nugard.firebaseapp.com',
    storageBucket: 'nugard.appspot.com',
  );
}
